#!/usr/bin/env python3
"""Generate a KiCad custom-rules file (.kicad_dru) from approved constraints.

Only approved constraints are used (CLAUDE.md rule 6). The header records the schema version
and a SHA-256 of the approved constraints (rule 7: ruleset hash). Types with no DRU
equivalent (max_distance: placement; impedance: needs the stackup; netclass: project file,
orchestrator/netclass.py) are listed, not emitted.

Usage:
    python3 orchestrator/dru.py constraints.json [-o board.kicad_dru]
Exit: 0 ok, 1 invalid constraints, 2 unreadable input.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from decimal import Decimal
from pathlib import Path

import constraints as cs

NOT_EXPRESSIBLE = {
    "max_distance": "placement constraint, used by the engine (phase 2)",
    "impedance": "needs the board stackup to become widths and gaps",
    "netclass": "written to the project file by orchestrator/netclass.py",
}


class Unsupported(ValueError):
    """A constraint that cannot be written as a DRU rule."""


def mm(nm: int) -> str:
    """Integer nanometres as an exact DRU length, e.g. 127000 -> '0.127mm'."""
    return f"{Decimal(nm).scaleb(-6).normalize():f}mm"


def _quote(name: str) -> str:
    if any(ch in name for ch in "'\"\\\n"):
        raise Unsupported(f"name {name!r} contains a quote, backslash or newline")
    return f"'{name}'"


def _match(sel: dict, side: str) -> str:
    if "netclass" in sel:
        return f"{side}.NetClass == {_quote(sel['netclass'])}"
    terms = [f"{side}.NetName == {_quote(n)}" for n in sel["nets"]]
    return terms[0] if len(terms) == 1 else "(" + " || ".join(terms) + ")"


def rules_for(c: dict) -> tuple[str, list[str]]:
    """(condition, constraint clauses) for one constraint; Unsupported if not expressible."""
    t = c["type"]
    if t in NOT_EXPRESSIBLE:
        raise Unsupported(NOT_EXPRESSIBLE[t])
    if t == "clearance":
        cond = _match(c["a"], "A")
        if "b" in c:
            cond += " && " + _match(c["b"], "B")
        return cond, [f"(constraint clearance (min {mm(c['min_nm'])}))"]
    if t == "track_width":
        parts = " ".join(
            f"({k} {mm(c[f'{k}_nm'])})" for k in ("min", "opt", "max") if f"{k}_nm" in c
        )
        return _match(c["on"], "A"), [f"(constraint track_width {parts})"]
    if t == "diff_pair":
        # Width and gap are routing targets (opt); impedance is checked separately.
        clauses = [
            f"(constraint track_width (opt {mm(c['width_nm'])}))",
            f"(constraint diff_pair_gap (opt {mm(c['gap_nm'])}))",
        ]
        if "max_uncoupled_nm" in c:
            clauses.append(f"(constraint diff_pair_uncoupled (max {mm(c['max_uncoupled_nm'])}))")
        if "max_skew_nm" in c:
            clauses.append(f"(constraint skew (max {mm(c['max_skew_nm'])}))")
        return _match({"nets": [c["p"], c["n"]]}, "A"), clauses
    if t == "length_match":
        clauses = [f"(constraint skew (max {mm(c['tolerance_nm'])}))"]
        if "target_nm" in c:
            lo = max(c["target_nm"] - c["tolerance_nm"], 0)
            hi = c["target_nm"] + c["tolerance_nm"]
            clauses.append(f"(constraint length (min {mm(lo)}) (max {mm(hi)}))")
        return _match({"nets": c["nets"]}, "A"), clauses
    if t == "max_length":
        return _match(c["on"], "A"), [f"(constraint length (max {mm(c['max_nm'])}))"]
    raise Unsupported(f"no DRU mapping for type {t!r}")


def ruleset_hash(approved: list[dict]) -> str:
    blob = json.dumps(approved, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(blob).hexdigest()


def _comment(text: str) -> str:
    return "# " + " ".join(str(text).split())


def render(approved: list[dict]) -> tuple[str, list[str]]:
    """The .kicad_dru text for approved constraints, plus 'id (type): reason' for skipped ones."""
    lines = [
        "(version 1)",
        _comment(f"generated by kicad-autolayout orchestrator/dru.py, schema v{cs.SCHEMA_VERSION}"),
        _comment(f"ruleset sha256 {ruleset_hash(approved)}"),
    ]
    skipped = []
    for c in approved:
        try:
            cond, clauses = rules_for(c)
        except Unsupported as e:
            skipped.append(f"{c['id']} ({c['type']}): {e}")
            lines += ["", _comment(f"not emitted: {c['id']} ({c['type']}): {e}")]
            continue
        src = c["source"]
        lines += [
            "",
            _comment(f"{c['id']}: {src['doc']} p.{src['page']}, approved by {c['approved_by']}"),
            f'(rule "kal:{c["id"]}"',
            f'\t(condition "{cond}")',
        ]
        lines += [f"\t{clause}" for clause in clauses]
        lines[-1] += ")"
    return "\n".join(lines) + "\n", skipped


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("constraints", type=Path)
    p.add_argument("-o", "--output", type=Path, help="write the rules here (default: stdout)")
    args = p.parse_args(argv)

    try:
        doc = cs.load_file(args.constraints)
    except cs.FileError as e:
        print(f"dru: {e}", file=sys.stderr)
        return 2
    constraints, errors = cs.validate(doc)
    if errors:
        for e in errors:
            print(f"dru: {e}", file=sys.stderr)
        return 1

    approved = cs.approved_only(constraints)
    text, skipped = render(approved)
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    emitted = len(approved) - len(skipped)
    unapproved = len(constraints) - len(approved)
    print(f"dru: {emitted} rule(s); {unapproved} unapproved skipped", file=sys.stderr)
    for s in skipped:
        print(f"dru: not emitted: {s}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
